services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474 
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/Thanos911
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - marvel-network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - marvel-network
  server:
    image: marvel-ai-agent:latest
    container_name: server
    env_file:
      - .env
    depends_on:
      - neo4j
      - redis
    ports:
      - 8000:8000
    volumes:
      - ./logs:/home/logs
    networks:
      - marvel-network

networks:
  marvel-network:
    driver: bridge
volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: